[project]
name = "datacommons-agents"
dynamic = ["version"]
description = "Data Commons Sample Agents"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "google-adk",
    "google-adk[eval]",
    "datacommons-mcp",
]
urls = {Homepage = "https://github.com/datacommonsorg/agent-toolkit"}

#[project.scripts]
#datacommons-agents = "datacommons_agents.cli:cli"

[build-system]
requires = ["uv", "setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
datacommons_mcp = ["*.evalset.json"]

[tool.setuptools.dynamic]
version = {attr = "datacommons_agents.version.__version__"}
