[project]
name = "datacommons-mcp"
dynamic = ["version"]
description = "Data Commons MCP server."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn",
    "fastmcp",
    "requests",
    "datacommons-client",
    "pydantic>=2.11.7",
    "pytest-asyncio>=1.1.0",
]
urls = {Homepage = "https://github.com/datacommonsorg/agent-toolkit"}

[project.scripts]
datacommons-mcp = "datacommons_mcp.cli:cli"

[project.optional-dependencies]
test = [
  "pytest>=8.4.1",
  "pytest-asyncio>=1.1.0",
]

[build-system]
requires = ["uv", "setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
datacommons_mcp = ["*.json"]

[tool.setuptools.dynamic]
version = {attr = "datacommons_mcp.version.__version__"}
